export const recentLogs = [
  {
    id: 1234567890,
    deleted: false,
    createdBy: "John Per",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    timecode: { hour: 5, minute: 30, second: 45, frame: 12 },
    localDate: { year: 2024, month: 4, day: 22 },
    projectName: "test1",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 987654321,
    deleted: true,
    createdBy: "Alice Smith",
    body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    timecode: { hour: 10, minute: 15, second: 20, frame: 8 },
    localDate: { year: 2023, month: 9, day: 12 },
    projectName: "test2",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 246813579,
    deleted: false,
    createdBy: "Emily Johnson",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    timecode: { hour: 15, minute: 45, second: 10, frame: 18 },
    localDate: { year: 2025, month: 6, day: 30 },
    projectName: "test3",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1357924680,
    deleted: true,
    createdBy: "Michael Brown",
    body: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    timecode: { hour: 3, minute: 20, second: 55, frame: 6 },
    localDate: { year: 2024, month: 8, day: 15 },
    projectName: "test4",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9876543210,
    deleted: false,
    createdBy: "Sophia Martinez",
    body: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
    timecode: { hour: 12, minute: 10, second: 30, frame: 14 },
    localDate: { year: 2023, month: 12, day: 7 },
    projectName: "test5",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3692581470,
    deleted: true,
    createdBy: "Daniel Wilson",
    body: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    timecode: { hour: 8, minute: 55, second: 40, frame: 22 },
    localDate: { year: 2025, month: 2, day: 18 },
    projectName: "test6",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2468013579,
    deleted: false,
    createdBy: "Olivia Taylor",
    body: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
    timecode: { hour: 20, minute: 5, second: 15, frame: 18 },
    localDate: { year: 2024, month: 5, day: 9 },
    projectName: "test7",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1230987654,
    deleted: false,
    createdBy: "David Anderson",
    body: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
    timecode: { hour: 18, minute: 40, second: 5, frame: 10 },
    localDate: { year: 2023, month: 10, day: 29 },
    projectName: "test8",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
