export const recentLogs = [
  {
    id: 1234567890,
    deleted: false,
    createdByFullName: "John Per",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    timecode: { hours: 5, minutes: 30, seconds: 45, frames: 12 },
    localDate: { year: 2024, month: 4, day: 22 },
    projectName: "test1",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 987654321,
    deleted: true,
    createdByFullName: "Alice Smith",
    body: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    timecode: { hours: 10, minutes: 15, seconds: 20, frames: 8 },
    localDate: { year: 2023, month: 9, day: 12 },
    projectName: "test2",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 246813579,
    deleted: false,
    createdByFullName: "Emily Johnson",
    body: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    timecode: { hours: 15, minutes: 45, seconds: 10, frames: 18 },
    localDate: { year: 2025, month: 6, day: 30 },
    projectName: "test3",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1357924680,
    deleted: true,
    createdByFullName: "Michael Brown",
    body: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
    timecode: { hours: 3, minutes: 20, seconds: 55, frames: 6 },
    localDate: { year: 2024, month: 8, day: 15 },
    projectName: "test4",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 9876543210,
    deleted: false,
    createdByFullName: "Sophia Martinez",
    body: "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
    timecode: { hours: 12, minutes: 10, seconds: 30, frames: 14 },
    localDate: { year: 2023, month: 12, day: 7 },
    projectName: "test5",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3692581470,
    deleted: true,
    createdByFullName: "Daniel Wilson",
    body: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
    timecode: { hours: 8, minutes: 55, seconds: 40, frames: 22 },
    localDate: { year: 2025, month: 2, day: 18 },
    projectName: "test6",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2468013579,
    deleted: false,
    createdByFullName: "Olivia Taylor",
    body: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
    timecode: { hours: 20, minutes: 5, seconds: 15, frames: 18 },
    localDate: { year: 2024, month: 5, day: 9 },
    projectName: "test7",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 1230987654,
    deleted: false,
    createdByFullName: "David Anderson",
    body: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
    timecode: { hours: 18, minutes: 40, seconds: 5, frames: 10 },
    localDate: { year: 2023, month: 10, day: 29 },
    projectName: "test8",
    project: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
