services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongodb:27017/weblogger"
    env_file:
      - .env
    ports:
      - 5173:5173
    networks:
      - node-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6-jammy
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    networks:
      - node-network
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  node-network:
    driver: bridge
