services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongo1:27017/weblogger?replicaSet=rs0&directConnection=true"
    env_file:
      - .env
    ports:
      - 5173:5173
    depends_on:
      mongo1:
        condition: service_healthy
  mongo1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

volumes:
  mongo1_data:
  mongo1_config:
