export const editColors = {
  blue: {
    css: "blue-500",
    avid: "blue",
    ppro: "4294741314",
    davinci: "ResolveColorBlue",
    fcpx: "",
  },
  cyan: {
    css: "cyan-500",
    avid: "cyan",
    ppro: "4292277273",
    davinci: "ResolveColorCyan",
    fcpx: "",
  },
  green: {
    css: "green-500",
    avid: "green",
    ppro: false,
    davinci: "ResolveColorGreen",
    fcpx: "",
  },
  yellow: {
    css: "yellow-500",
    avid: "yellow",
    ppro: "4281049552",
    davinci: "ResolveColorYellow",
    fcpx: "",
  },
  red: {
    css: "red-500",
    avid: "red",
    ppro: "4281740498",
    davinci: "ResolveColorRed",
    fcpx: "",
  },
  pink: {
    css: "pink-500",
    avid: "magenta",
    ppro: false,
    davinci: false,
    fcpx: "",
  },
  black: {
    css: "neutral-800",
    avid: "black",
    ppro: false,
    davinci: false,
    fcpx: "",
  },
  white: {
    css: "neutral-100",
    avid: "white",
    ppro: "4294967295",
    davinci: false,
    fcpx: "",
  },
};
