export const editColors = {
  blue: {
    css: "blue-500",
    hex: "#3b82f6",
    cssText: "white",
    textHex: "#ffffff",
    avid: "blue",
    ppro: "4294741314",
    davinci: "ResolveColorBlue",
    fcpx: "",
  },
  cyan: {
    css: "cyan-500",
    hex: "#06b6d4",
    cssText: "white",
    textHex: "#ffffff",
    avid: "cyan",
    ppro: "4292277273",
    davinci: "ResolveColorCyan",
    fcpx: "",
  },
  green: {
    css: "green-500",
    hex: "#22c55e",
    cssText: "black",
    textHex: "#000000",
    avid: "green",
    ppro: "4281828977",
    davinci: "ResolveColorGreen",
    fcpx: "",
  },
  yellow: {
    css: "yellow-500",
    hex: "#eab308",
    cssText: "black",
    textHex: "#000000",
    avid: "yellow",
    ppro: "4281049552",
    davinci: "ResolveColorYellow",
    fcpx: "",
  },
  red: {
    css: "red-500",
    hex: "#ef4444",
    cssText: "white",
    textHex: "#ffffff",
    avid: "red",
    ppro: "4281740498",
    davinci: "ResolveColorRed",
    fcpx: "",
  },
  pink: {
    css: "pink-500",
    hex: "#ec4899",
    cssText: "white",
    textHex: "#ffffff",
    avid: "magenta",
    ppro: "4289825711",
    davinci: false,
    fcpx: "",
  },
  black: {
    css: "neutral-800",
    hex: "#262626",
    cssText: "white",
    textHex: "#ffffff",
    avid: "black",
    ppro: " ",
    davinci: false,
    fcpx: "",
  },
  white: {
    css: "neutral-100",
    hex: "#f5f5f5",
    cssText: "black",
    textHex: "#000000",
    avid: "white",
    ppro: "4294967295",
    davinci: false,
    fcpx: "",
  },
};
